openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Playback Info"
tags:
  - name: Playback Info
    description: >-
      Holds playback information per asset. An asset can be a recording, catchup, VOD and so on.
      This resource allows storing information like playback position and last viewed for such assets.
servers:
  - url: 'https://demo.aminocom.com/api/playback_info/v1/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: []         # use the same name as above
paths:

  # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
  # Playback Info
  # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/assets/{asset_type}/{asset_id}:
    put:
      description: |
        * **Available since:** 2020-01 (BPLAT-12229)
      summary: Create/update a playback info of a given asset for a given user profile
      tags:
        - Playback Info
      operationId: putPlaybackInfo
      parameters:
        - in: path
          name: user_profile_id
          required: true
          description: The identity of the user profile to create playback info.
          schema:
            type: string
        - in: path
          name: asset_type
          required: true
          description: The asset type of the playback info.
          schema:
            type: string
            enum: ["recording", "catchup", "vod"]
        - in: path
          name: asset_id
          required: true
          description: The asset id of the playback info.
          schema:
            type: string

      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "../../snippets/PlaybackInfo/PlaybackInfoRequestBody.yml#/PlaybackInfoRequestBodyEntity"

      responses:
        204:
          description: |
            The resource was updated successfully, no response body is needed

        400:
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "2d3ba0ea-0aca-11ea-b2d0-4bc6fcad2537"
                    status: "400"
                    code: "10100"
                    title: "Bad Request"
                    detail: "- Must have keys { \"data\" }"

        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "2d3ba0ea-0aca-11ea-b2d0-4bc6fcad2537"
                    status: "400"
                    code: "10100"
                    title: "Bad Request"
                    detail: "Invalid authorization token: Token not provided in header"

        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "934dc960-a733-409f-a000-c112b64c8553"
                    status: "403"
                    code: "51"
                    title: "Forbidden"
                    detail: "Authenticated user with Profile ID \"00000000-1111-2222-3333-444444444444\" not authorized to perform action"

    get:
      description: |
        * **Available since:** 2020-01 (BPLAT-12230)
      summary: Get the current playback info for one given asset
      tags:
        - Playback Info
      operationId: getPlaybackInfo
      parameters:
        - in: path
          name: user_profile_id
          required: true
          description: The identity of the user profile to get the playback info for.
          schema:
            type: string
        - in: path
          name: asset_type
          required: true
          description: The asset type of the playback info.
          schema:
            type: string
            enum: ["recording", "catchup", "vod"]
        - in: path
          name: asset_id
          required: true
          description: The asset id of the playback info.
          schema:
            type: string

      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: "object"
                required:
                  - data
                properties:
                  data:
                    $ref: "../../snippets/PlaybackInfo/PlaybackInfoEntity.yml#/PlaybackInfoEntity"

        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "2d3ba0ea-0aca-11ea-b2d0-4bc6fcad2537"
                    status: "404"
                    code: "30401"
                    title: "Playback info not found"
                    detail: 'Playback info for user profile "4a7d0b30-aa6d-4730-823e-c1c27b446c05", type "recording" and ID "4a1e81ed-b3f0-452b-b567-db54e885bab7" was not found'


  # ------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

  /user_profiles/{user_profile_id}/assets/{asset_type}:
    get:
      description: |
        * **Available since:** 2020-01 (BPLAT-12231)
      tags:
        - Playback Info
      operationId: getPlaybackInfoIndex
      parameters:
        - in: path
          name: user_profile_id
          required: true
          description: The identity of the user profile to get the playback info for.
          schema:
            type: string
        - in: path
          name: asset_type
          required: true
          description: The asset type of the playback info.
          schema:
            type: string
            enum: ["recording", "catchup", "vod"]
        - in: query
          name: filter
          description: >-
            Please see http://jsonapi.org/recommendations/#filtering. The following are attributes to filter on: [group_id]
          schema:
            type: string

      responses:
        200:
          description: Successful response
          content:
            application/json:
              schema:
                type: "object"
                required:
                  - data
                properties:
                  data:
                    type: array
                    items:
                      $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/PlaybackInfo/PlaybackInfoEntity.yml#/PlaybackInfoEntity"

        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "2d3ba0ea-0aca-11ea-b2d0-4bc6fcad2537"
                    status: "404"
                    code: "30401"
                    title: "Playback info not found"
                    detail: 'Playback info for user profile "4a7d0b30-aa6d-4730-823e-c1c27b446c05", type "recording" and ID "4a1e81ed-b3f0-452b-b567-db54e885bab7" was not found'
