openapi: 3.0.0
info:
  description: >-
    This API allows users to change properties of their User, such as the user password.
  version: "2.0.0"
  title: "User Preferences"
tags:
  - name: User Preferences
    description: >-
      Allows changing attributes of the user, such as the user password.
  - name: Password Reset
    description: >-
      Allows resetting a password that has been forgotten through a password reset email process.
servers:
  - url: 'https://demo.aminocom.com/api/users/v2/'
components:
  securitySchemes:
    bearerAuth:            # arbitrary name for the security scheme
      type: http
      scheme: bearer
      bearerFormat: JWT    # optional, arbitrary value for documentation purposes
security:
  - bearerAuth: []         # use the same name as above

paths:
  # -------------------------------------------------------------------------------------------------------------------------------------
  # USER PREFERENCES
  # -------------------------------------------------------------------------------------------------------------------------------------

  /users/{user_id}:
    patch:
      description: |
        * **Available since:** 2020-02 BPLAT-12511
      tags:
        - User Preferences
      summary: Update a user account
      operationId: updateUser
      parameters:
        - in: path
          name: user_id
          required: true
          description: The identity of the user to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/UserConfiguration/UserEntity.yml#/UserPatchRequestBody"
      responses:
        204:
          description: Successful response, the user attributes were updated successfully as specified. No content returned.
        404:
          description: The user to be updated does not exist.
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "27175c94-4987-11ea-bf0a-0b4d2657da40"
                    status: "404"
                    code: "30501"
                    title: "Not found"
                    detail: 'User with ID "4422" does not exist'
        401:
          description: The request was rejected.
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "063ca86c-4987-11ea-9f97-130e9fe21f9f"
                    status: "401"
                    code: "30502"
                    title: "Unauthorized"
                    detail: 'Password verification failed.'


  # -------------------------------------------------------------------------------------------------------------------------------------
  # PASSWORD RESET
  # -------------------------------------------------------------------------------------------------------------------------------------
  /reset_password:
    post:
      description: |
        * **Available since:** 2020-02 BPLAT-12525
      tags:
        - Password Reset
      summary: Request password reset email
      operationId: requestResetPassword
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  example: "test@24i.com"

      responses:
        204:
          description: Successful response, the requested reset password email was sent. No content returned. Also returned if the user email does not exist.
# -------------------------------------------------------------------------------------------------------------------------------------

  /confirm_reset_password:
    post:
      description: |
        * **Available since:** 2020-02 BPLAT-12526
      tags:
        - Password Reset
      summary: Confirm password reset email
      operationId: confirmResetPassword
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - reset_code
                - new_password
              properties:
                email:
                  type: string
                  example: "test@24i.com"
                reset_code:
                  type: string
                  example: "6b76938f079574a6f7ce862e83b6e213"
                new_password:
                  type: string
                  example: "foorBar1234"

      responses:
        204:
          description: Successful response, the requested reset password was confirmed. No content returned.
        404:
          description: The user for a provided email does not exist.
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "27175c94-4987-11ea-bf0a-0b4d2657da40"
                    status: "404"
                    code: "30501"
                    title: "Not found"
                    detail: 'User with email "foo@email.com" does not exist'
        400:
          description: Reset code provided was invalid.
          content:
            application/json:
              schema:
                $ref: "https://raw.githubusercontent.com/booxmedialtd/api-documentation/master/rest/snippets/General/JsonApiErrorEntity.yml#/JsonApiErrorEntity"
              example:
                errors:
                  - id: "27175c94-4987-11ea-bf0a-0b4d2657da40"
                    status: "400"
                    code: "10100"
                    title: "Invalid ResetCode"
                    detail: 'Invalid reset code: 6b76938f079574a6f7ce862e83b6e213'